### PR TITLE
switch to @nextcloud/eslint-plugin

### PR DESCRIPTION
**Pull request by korelstar**
`eslint-plugin-nextcloud` was renamed to `@nextcloud/eslint-plugin`. At some point in the future, this package could also be renamed ...

### CODE REVIEW

**Comment by korelstar** [comment]
can this be merged or should we wait for the review from @ChristophWurst ?

**Comment by skjnldsv** [comment]
@ChristophWurst returns today :)

**Comment by rullzer** [comment]
> @ChristophWurst returns today :)

Tomorrow. Since the 6th is also a public holiday over there (because why not!)

**Comment by korelstar** [comment]
This is still not part of any release. Maybe an automated release process for this repository makes sense?

What about renaming this package itself?

**Comment by ChristophWurst** [comment]
I guess I should have permissions to publish a new release. Mind sending a PR with the necessary changes for the rename?

**Comment by korelstar** [comment]
I can do this (later), but I can't rename this repository (like [`@nextcloud/eslint-plugin`](https://github.com/nextcloud/eslint-plugin) to `nextcloud/eslint-config`). This has to be done by someone else ...

**Comment by ChristophWurst** [comment]
I can do that. But the github repo name doesn't matter for the npm package, except for any links pointing to it :)

**Pull request merged**
